name: flutter_clean_architecture
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  auto_route: ^7.4.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  auto_route_generator: ^7.1.1
  get_it: ^7.6.0
  dio: ^5.2.1+1
  shared_preferences: ^2.1.2
  slang: ^3.19.0
  slang_flutter:
  injectable: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  flutter_gen_runner:
  slang_build_runner:
  injectable_generator: 
  
flutter_gen:
  output: lib/gen
  line_length: 100
  null_safety: true

  integrations:
    flutter_svg: true

  assets:
    enabled: true

  fonts:
    enabled: true

flutter:

  uses-material-design: true

  assets:
    - assets/env/
    - assets/icons/
    - assets/images/
    - assets/fonts/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
